"""Default paths and hyperparameters for local experiments."""

from __future__ import annotations

from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parent

DEFAULT_DATA_PATH = (
    PROJECT_ROOT
    / "data"
    / "game24.jsonl"
)

DEFAULT_GSM8K_DATA_PATH = (
    PROJECT_ROOT
    / "data"
    / "gsm8K.json"
)


DEFAULT_RESULTS_DIR = PROJECT_ROOT / "results"

DEFAULT_RANDOM_SEED = 42

DEFAULT_LIMIT = 10

DEFAULT_MODEL_NAME = "qwen2.5:3b"
DEFAULT_OLLAMA_BASE_URL = "http://localhost:11434"

DEFAULT_TEMPERATURE = 0.0
DEFAULT_MAX_TOKENS = 512
DEFAULT_CONTEXT_LENGTH = 2048
DEFAULT_BASELINE_MAX_TOKENS = 128
DEFAULT_COT_MAX_TOKENS = 384
DEFAULT_GSM8K_BASELINE_MAX_TOKENS = 256
DEFAULT_GSM8K_COT_MAX_TOKENS = 768
DEFAULT_SELF_CONSISTENCY_SAMPLES = 5
DEFAULT_SELF_CONSISTENCY_TEMPERATURE = 0.7
DEFAULT_GSM8K_TOT_BRANCH_FACTOR = 3
DEFAULT_GSM8K_TOT_MAX_DEPTH = 6
DEFAULT_GSM8K_TOT_STEP_MAX_TOKENS = 512
DEFAULT_GSM8K_TOT_GENERATION_TEMPERATURE = 0.7
DEFAULT_VALUE_MAX_TOKENS = 128
DEFAULT_KEEP_ALIVE = "30m"

DEFAULT_REQUEST_TIMEOUT = 300

DEFAULT_TOT_STRATEGY = "bfs"

DEFAULT_VALUE_BATCH_SIZE = 12

DEFAULT_BEAM_WIDTH = 5

# None means DFS explores every ranked child.
DEFAULT_DFS_BRANCH_LIMIT = 3

DEFAULT_ASTAR_HEURISTIC_WEIGHT = 2.0

DEFAULT_MCTS_ITERATIONS = 100

DEFAULT_MCTS_EXPLORATION_WEIGHT = 1.4

DEFAULT_MAX_EXPANDED_NODES = 100
